namespace Steema.TeeChart.Drawing
{
    using Steema.TeeChart;
    using System;
    using System.Drawing;
    using System.Drawing.Drawing2D;
    using System.IO;
    using System.Text;

    public class Graphics3DVML : Graphics3DVec
    {
        public Graphics3DVML(Stream istream, Chart c) : base(istream, c)
        {
            base.iCanvasType = CanvasType.VML;
            base.swFromStream = new StreamWriter(istream, Encoding.Unicode);
            this.AddToStream("<!-- Generated by TeeChart -->");
            this.AddToStream("<body>");
            this.AddToStream("<html>");
            this.AddToStream("<xml:namespace prefix=\"v\"/>");
            this.AddToStream(@"<style>v\:* {behavior=url(#default#VML)}</style>");
        }

        public override void Arc(int x1, int y1, int x2, int y2, float startAngle, float sweepAngle)
        {
            if (base.Pen.Visible)
            {
                int num = 90 + Utils.Round(startAngle);
                int num2 = num + Utils.Round(sweepAngle);
                int num3 = Utils.Round((float) (x2 - x1));
                int num4 = Utils.Round((float) (y2 - y1));
                base.m_string = "<v:arc style=\"position:absolute;left:" + x1.ToString() + ";top:" + y1.ToString();
                string str = base.m_string;
                base.m_string = str + ";width:" + num3.ToString() + ";height:" + num4.ToString() + "\"";
                string str2 = base.m_string;
                base.m_string = str2 + " startangle=\"" + num.ToString() + "\" endangle=\"" + num2.ToString() + "\"";
                base.m_string = base.m_string + " filled=\"f\"";
                if (base.Pen.Visible)
                {
                    base.m_string = base.m_string + " strokecolor=" + this.VMLColor(base.Pen.Color, false);
                }
                else
                {
                    base.m_string = base.m_string + " stroked=\"f\"";
                }
                base.m_string = base.m_string + ">";
                this.AddToStream(base.m_string);
            }
        }

        public override void Arc(int x1, int y1, int x2, int y2, int x3, int y3, int x4, int y4)
        {
            if (base.Pen.Visible)
            {
                this.PrepareShape();
                base.m_string = "<v:path v=\"ar ";
                string str = base.m_string;
                base.m_string = str + this.PointToStr(x1, y1) + " " + this.PointToStr(x2, y2) + " " + this.PointToStr(x3, y3) + " " + this.PointToStr(x4, y4);
                base.m_string = base.m_string + " e\"/>";
                this.AddToStream(base.m_string);
                this.AddToStream("</v:shape>");
            }
        }

        public override void ClearClipRegions()
        {
        }

        public override void ClipEllipse(Rectangle r)
        {
        }

        public override void ClipPolygon(params Point[] p)
        {
        }

        public override void ClipRectangle(Rectangle r)
        {
        }

        protected override void DoText(int x, int y, string text, double degAngle, Color c)
        {
            float num = 0f;
            if (base.TextAlign == StringAlignment.Center)
            {
                num = this.TextWidth(text) * 0.5f;
            }
            else if (base.TextAlign == StringAlignment.Far)
            {
                num = this.TextWidth(text);
            }
            x -= Utils.Round(num);
            if (degAngle == 0.0)
            {
                base.m_string = "<v:textbox style=\"position:absolute; left:" + x.ToString() + "; top:" + y.ToString();
                base.m_string = base.m_string + "; color:" + this.VMLColor(c, true) + "; text-align:left; ";
                base.m_string = base.m_string + this.FontProperties(base.Font) + "\">";
                base.m_string = base.m_string + text;
                base.m_string = base.m_string + "</v:textbox>";
            }
            else
            {
                num = this.TextWidth(text);
                float num6 = this.TextHeight(text);
                double d = (degAngle * 3.1415926535897931) / 180.0;
                double num8 = Math.Cos(d);
                double num9 = Math.Sin(d);
                y += Utils.Round((double) (num6 * 0.5));
                int num2 = Utils.Round((double) (x + (num9 * num6)));
                int num3 = Utils.Round((double) (y + (num8 * num6)));
                int num4 = Utils.Round((double) (x + ((num8 * num) + (num9 * num6))));
                int num5 = Utils.Round((double) (y + ((-num9 * num) + (num8 * num6))));
                if (num2 == num4)
                {
                    num4++;
                }
                if (num3 == num5)
                {
                    num5++;
                }
                if ((degAngle > 90.0) && (degAngle < 270.0))
                {
                    num2 -= Utils.Round((double) ((num * num8) + (num6 * num9)));
                    num4 -= Utils.Round((double) ((num * num8) + (num6 * num9)));
                }
                base.m_string = "<v:line from=\"" + num2.ToString() + "," + num3.ToString() + "\" to=\"";
                string str = base.m_string;
                base.m_string = str + num4.ToString() + "," + num5.ToString() + "\" style=\"position: absolute\">\r\n";
                base.m_string = base.m_string + "  <v:fill on=\"True\" color=" + this.VMLColor(c, false) + "/>\r\n";
                base.m_string = base.m_string + "  <v:path textpathok=\"True\"/>\r\n";
                base.m_string = base.m_string + "  <v:textpath on=\"True\" trim=\"True\" string=\"" + text + "\"";
                base.m_string = base.m_string + "; style=\"font: ";
                if (base.Font.Italic)
                {
                    base.m_string = base.m_string + "italic normal ";
                }
                else
                {
                    base.m_string = base.m_string + "normal normal ";
                }
                if (base.Font.Bold)
                {
                    base.m_string = base.m_string + "bold ";
                }
                else
                {
                    base.m_string = base.m_string + "normal ";
                }
                base.m_string = base.m_string + base.Font.Size.ToString() + "pt " + base.Font.Name;
                base.m_string = base.m_string + "\"/>\r\n";
                base.m_string = base.m_string + "</v:line>";
            }
            this.AddToStream(base.m_string);
        }

        public override void Draw(Rectangle r, Image image, bool transparent)
        {
        }

        public override void Draw(int x, int y, Image image)
        {
        }

        public override void DrawBeziers(params Point[] p)
        {
        }

        private void DrawBrushImage(Rectangle rect)
        {
        }

        public override void DrawPath(Pen pen, GraphicsPath path)
        {
        }

        public override void Ellipse(int x1, int y1, int x2, int y2)
        {
            if (base.Brush.Visible || base.Pen.Visible)
            {
                int num = Utils.Round((float) (y2 - y1));
                int num2 = Utils.Round((float) (x2 - x1));
                base.m_string = "<v:oval style=\"position:absolute;left:" + x1.ToString() + ";top:";
                string str = base.m_string;
                base.m_string = str + y1.ToString() + ";height:" + num.ToString() + ";width:" + num2.ToString() + "\" fillcolor=";
                base.m_string = base.m_string + this.VMLColor(base.Brush.Color, false) + this.VMLPen("oval");
                this.AddToStream(base.m_string);
            }
        }

        public override void EraseBackground(int left, int top, int right, int bottom)
        {
        }

        public override void FillRegion(Brush brush, Region region)
        {
        }

        private string FontProperties(ChartFont f)
        {
            base.m_string = "font-family:" + f.Name.ToString() + "; font-size:" + f.Size.ToString() + "pt; ";
            if (f.Bold)
            {
                base.m_string = base.m_string + " font-weight=bold;";
            }
            if (f.Italic)
            {
                base.m_string = base.m_string + " font-style=italic;";
            }
            if (f.Underline)
            {
                base.m_string = base.m_string + " text-decoration=underline;";
            }
            if (f.Strikeout)
            {
                base.m_string = base.m_string + " text-decoration=line-through;";
            }
            return base.m_string;
        }

        protected internal override void InitWindow(Graphics graphics, Aspect a, Rectangle r, int MaxDepth)
        {
            base.InitWindow(graphics, a, r, MaxDepth);
            base.m_string = "<v:group style=\"" + this.TheBounds() + "\" ";
            base.m_string = base.m_string + "coordsize=\"" + this.PointToStr(base.chart.ChartBounds.Width, base.chart.ChartBounds.Height) + "\"";
            base.m_string = base.m_string + " coordorigin=\"" + this.PointToStr(base.chart.ChartBounds.Top, base.chart.ChartBounds.Left) + "\">";
            this.AddToStream(base.m_string);
        }

        private void InternalPolygon(ChartBrush br, ChartPen pn, bool PolyLine, params PointDouble[] p)
        {
            if (br.Visible || pn.Visible)
            {
                this.PrepareShape();
                base.m_string = "<v:path v=\"m " + this.PointToStr(p[0].X, p[0].Y) + " l ";
                for (int i = 1; i <= p.GetUpperBound(0); i++)
                {
                    base.m_string = base.m_string + this.PointToStr(p[i].X, p[i].Y) + " ";
                }
                if (PolyLine)
                {
                    base.m_string = base.m_string + " e\"/>";
                }
                else
                {
                    base.m_string = base.m_string + " x e\"/>";
                }
                this.AddToStream(base.m_string);
                this.AddToStream("</v:shape>");
            }
        }

        private void InternalPolygon(ChartBrush br, ChartPen pn, bool PolyLine, params Point[] p)
        {
            if (br.Visible || pn.Visible)
            {
                this.PrepareShape();
                base.m_string = "<v:path v=\"m " + this.PointToStr(p[0].X, p[0].Y) + " l ";
                for (int i = 1; i <= p.GetUpperBound(0); i++)
                {
                    base.m_string = base.m_string + this.PointToStr(p[i].X, p[i].Y) + " ";
                }
                if (PolyLine)
                {
                    base.m_string = base.m_string + " e\"/>";
                }
                else
                {
                    base.m_string = base.m_string + " x e\"/>";
                }
                this.AddToStream(base.m_string);
                this.AddToStream("</v:shape>");
            }
        }

        protected override void InternalRect(ChartBrush b, Rectangle r, bool UsePen, bool IsRound)
        {
            if (b.Visible || (UsePen && base.Pen.Visible))
            {
                base.m_string = "<v:";
                string element = "rect";
                if (IsRound)
                {
                    element = "roundrect";
                }
                base.m_string = base.m_string + element;
                base.m_string = base.m_string + " style=\"position:absolute;left:";
                string str3 = base.m_string;
                base.m_string = str3 + r.Left.ToString() + ";top:" + r.Top.ToString() + ";width:";
                int num = r.Width - 1;
                base.m_string = base.m_string + num.ToString() + ";height:";
                base.m_string = base.m_string + ((r.Height - 1)).ToString() + "\"";
                if (b.Visible)
                {
                    base.m_string = base.m_string + " fillcolor=" + this.VMLColor(b.Color, false);
                }
                else
                {
                    base.m_string = base.m_string + " filled=\"false\"";
                }
                if (UsePen && base.Pen.Visible)
                {
                    base.m_string = base.m_string + " strokecolor=" + this.VMLColor(base.Pen.Color, false);
                }
                else
                {
                    base.m_string = base.m_string + " stroked=\"f\"";
                }
                float num2 = 1f - (b.Transparency * 0.01f);
                if (num2 < 1f)
                {
                    string str2 = num2.ToString().Replace(',', '.');
                    base.m_string = base.m_string + " opacity=\"" + str2 + "\"";
                }
                base.m_string = base.m_string + this.VMLPen(element);
                this.AddToStream(base.m_string);
            }
        }

        public override void LineTo(int x, int y)
        {
            this.AddToStream("<v:line from=\"" + this.PointToStr(base.fx, base.fy) + "\" to=\"" + this.PointToStr(x, y) + this.VMLPen("line"));
            base.fx = x;
            base.fy = y;
        }

        private string PenStyle(ChartPen ipen)
        {
            if (ipen.Style == DashStyle.Solid)
            {
                return "";
            }
            return ipen.Style.ToString();
        }

        private string PenWidth(ChartPen ipen, string element)
        {
            if (ipen.Width > 1)
            {
                base.m_string = " " + element + "=\"" + ipen.Width.ToString() + "\"";
            }
            else
            {
                base.m_string = "";
            }
            return base.m_string;
        }

        public override void Pixel(int x, int y, int z, Color color)
        {
        }

        public override void Polygon(params PointDouble[] p)
        {
            this.Polygon(PointDouble.Round(p));
        }

        public override void Polygon(params Point[] p)
        {
            this.InternalPolygon(base.Brush, base.Pen, false, p);
        }

        public override void Polyline(params Point[] p)
        {
            this.InternalPolygon(base.Brush, base.Pen, true, p);
        }

        public override void PrepareDrawImage()
        {
        }

        private void PrepareShape()
        {
            base.m_string = "<v:shape style=\"position:absolute;" + this.TheBounds() + "\"";
            if (base.Brush.Visible)
            {
                base.m_string = base.m_string + " fillcolor=" + this.VMLColor(base.Brush.Color, false);
            }
            else
            {
                base.m_string = base.m_string + " filled=\"f\"";
            }
            if (base.Pen.Visible)
            {
                base.m_string = base.m_string + " strokecolor=" + this.VMLColor(base.Pen.Color, false);
            }
            else
            {
                base.m_string = base.m_string + " stroked=\"f\"";
            }
            float num = 1f - (base.Brush.Transparency * 0.01f);
            if (num < 1f)
            {
                string str = num.ToString().Replace(',', '.');
                base.m_string = base.m_string + " opacity=\"" + str + "\"";
            }
            base.m_string = base.m_string + ">";
            this.AddToStream(base.m_string);
        }

        public override void RotateLabel(int x, int y, string text, double rotDegree)
        {
            this.DoText(x, y, text, rotDegree, base.Font.Color);
        }

        public override void SetClipRegion(Region region)
        {
        }

        public override void ShowImage(Graphics g)
        {
            this.AddToStream("</v:group>");
            this.AddToStream("</body>");
            this.AddToStream("</html>");
        }

        private string TheBounds()
        {
            base.m_string = "width:" + base.chart.ChartBounds.Width.ToString();
            base.m_string = base.m_string + ";height:" + base.chart.ChartBounds.Height.ToString();
            return base.m_string;
        }

        protected internal override void TransparentEllipse(int x1, int y1, int x2, int y2)
        {
            int num = Utils.Round((float) (y2 - y1));
            int num2 = Utils.Round((float) (x2 - x1));
            base.m_string = "<v:oval style=\"position:absolute;left:" + x1.ToString() + ";top:";
            string str = base.m_string;
            base.m_string = str + y1.ToString() + ";height:" + num.ToString() + ";width:" + num2.ToString() + "\" filled=\"f\"";
            base.m_string = base.m_string + this.VMLPen("oval");
            this.AddToStream(base.m_string);
        }

        public override void UnClip()
        {
        }

        private string VMLColor(Color c, bool inter)
        {
            if (!inter)
            {
                base.m_string = "\"";
            }
            else
            {
                base.m_string = "";
            }
            if (c == Color.Black)
            {
                base.m_string = base.m_string + "black";
            }
            else if (c == Color.Silver)
            {
                base.m_string = base.m_string + "silver";
            }
            else if (c == Color.Gray)
            {
                base.m_string = base.m_string + "gray";
            }
            else if (c == Color.White)
            {
                base.m_string = base.m_string + "white";
            }
            else if (c == Color.Maroon)
            {
                base.m_string = base.m_string + "maroon";
            }
            else if (c == Color.Red)
            {
                base.m_string = base.m_string + "red";
            }
            else if (c == Color.Purple)
            {
                base.m_string = base.m_string + "purple";
            }
            else if (c == Color.Fuchsia)
            {
                base.m_string = base.m_string + "fuchsia";
            }
            else if (c == Color.Green)
            {
                base.m_string = base.m_string + "green";
            }
            else if (c == Color.Lime)
            {
                base.m_string = base.m_string + "lime";
            }
            else if (c == Color.Olive)
            {
                base.m_string = base.m_string + "olive";
            }
            else if (c == Color.Yellow)
            {
                base.m_string = base.m_string + "yellow";
            }
            else if (c == Color.Navy)
            {
                base.m_string = base.m_string + "navy";
            }
            else if (c == Color.Blue)
            {
                base.m_string = base.m_string + "blue";
            }
            else if (c == Color.Teal)
            {
                base.m_string = base.m_string + "teal";
            }
            else if (c == Color.Aqua)
            {
                base.m_string = base.m_string + "aqua";
            }
            else
            {
                base.m_string = base.m_string + "#" + c.R.ToString("X2");
                base.m_string = base.m_string + c.G.ToString("X2");
                base.m_string = base.m_string + c.B.ToString("X2");
            }
            if (!inter)
            {
                base.m_string = base.m_string + "\"";
            }
            return base.m_string;
        }

        private string VMLPen(string element)
        {
            base.m_string = "\" strokecolor=" + this.VMLColor(base.Pen.Color, false);
            if (base.Pen.Style != DashStyle.Solid)
            {
                string str = base.m_string;
                base.m_string = str + "><v:stroke dashstyle=\"" + this.PenStyle(base.Pen) + "\"" + this.PenWidth(base.Pen, "weight") + "/></v:" + element + ">";
            }
            else
            {
                base.m_string = base.m_string + this.PenWidth(base.Pen, "strokeweight") + "/>";
            }
            return base.m_string;
        }
    }
}

