namespace Steema.TeeChart
{
    using Steema.TeeChart.Languages;
    using System;

    public class Texts
    {
        public static string About;
        public static string AddNewGroup;
        public static string ADOConnection;
        public static string All;
        public static string AllDataFilter;
        public static string AllFilesFilter;
        public static string AllPictureFilter;
        public static string AllSeries;
        public const string AnnotationDesc = "Displays custom text at any location inside Chart.";
        public static string AnnotationSummary;
        public static string AnnotationTool;
        public static string AnswerVectorIndex;
        public static string ApplyColorPalette;
        public static string AsBMP;
        public static string AsEMF;
        public static string AsFlex;
        public static string AsGIF;
        public static string AsJPEG;
        public static string AskDataSet;
        public static string AskDataSource;
        public static string AskLanguage;
        public static string AsPCX;
        public static string AsPDF;
        public static string AsPNG;
        public static string AsPS;
        public static string AsSVG;
        public static string AsTIFF;
        public static string AsVML;
        public static string AsXAML;
        public const string AxisArrowDesc = "Displays clickable arrows at axis start and ending points, to scroll axis.";
        public static string AxisArrowSummary;
        public static string AxisArrowTool;
        public static string AxisDlgValue;
        public static string AxisIncrementNeg;
        public static string AxisLabels;
        public static string AxisLabelSep;
        public static string AxisLogBase;
        public static string AxisLogDateTime;
        public static string AxisLogNotPositive;
        public static string AxisMaxMin;
        public static string AxisMinMax;
        public const string AxisScrollDesc = "Allows the scrolling of Axes by mouse dragging";
        public static string AxisScrollSummary;
        public static string AxisScrollTool;
        public static string AxisTitle;
        public static string BannerTool;
        public const string BannerToolDesc = "Banner";
        public static string BannerToolSummary;
        public static string BaseLine;
        public static string BlackIsBackTheme;
        public static string BlueSkyTheme;
        public static string BMPFilter;
        public static string Border;
        public static string BottomAxis;
        public static string Box;
        public static string BrowseImage;
        public static string BusinessTheme;
        public static string CalcPeriod;
        public static string CalendarSeries;
        public static string Cancel;
        public static string CandleBar;
        public static string CandleNoClose;
        public static string CandleNoOpen;
        public static string CanNotCreateTempChart;
        public static string CanNotEmailChart;
        public static string CannotFindEditor;
        public static string CanNotFindTempPath;
        public static string CannotLoadChartFromURL;
        public static string CannotLoadSeriesDataFromURL;
        public static string CantDeleteAncestor;
        public const char CarriageReturnChar = '\r';
        public static string ChangeGroupName;
        public static string ChangeSeriesTitle;
        public const string CharForHeight = "W";
        public const string ChartImageDesc = "Displays a picture using the specified Series axes as boundaries. When the axis are zoomed or scrolled, the picture will follow the new boundaries.";
        public static string ChartImageSummary;
        public static string ChartWizard;
        public static string CheckPointerSize;
        public static string Circle;
        public static string CircularSeries;
        public static string ClassicTheme;
        public static string Clear;
        public static string ClearImage;
        public static string ClearMessage;
        public static string ClipSeries;
        public const string ClipSeriesDesc = "Clip to Series";
        public static string ClipSeriesSummary;
        public const string ColorBandDesc = "Displays a coloured rectangle (band) at the specified axis and position.";
        public static string ColorBandSummary;
        public static string ColorBandTool;
        public static string ColorGridSeriesRangeExceed;
        public const string ColorLineDesc = "Displays a draggable line across axes.";
        public static string ColorLineSummary;
        public static string ColorLineTool;
        public static string ColorPalette;
        public static string ColorRange;
        public static string Colors;
        public static string Column;
        public const char ColumnSeparator = '\x0006';
        public static string CommanMsg3D;
        public static string CommanMsgChart;
        public static string CommanMsgCopy;
        public static string CommanMsgDepth;
        public static string CommanMsgDepthing;
        public static string CommanMsgDepthLabel;
        public static string CommanMsgEdit;
        public static string CommanMsgMove;
        public static string CommanMsgMoveLabel;
        public static string CommanMsgMoving;
        public static string CommanMsgNormal;
        public static string CommanMsgNormalLabel;
        public static string CommanMsgNormalPieLabel;
        public static string CommanMsgPanel;
        public static string CommanMsgPieExploding;
        public static string CommanMsgPrint;
        public static string CommanMsgRotate;
        public static string CommanMsgRotateLabel;
        public static string CommanMsgRotating;
        public static string CommanMsgSave;
        public static string CommanMsgZoom;
        public static string CommanMsgZooming;
        public static string CommanMsgZoomLabel;
        public static string Cone;
        public static string Confirm;
        public const string Copyright = "\x00a9 2001-2008 by Steema Software";
        public static string Cover;
        public static string Cross;
        public static string Cube;
        public static string Current;
        public static string CursorTool;
        public const string CursorToolDesc = "Displays draggable Cursor lines on top of Series.";
        public static string CursorToolSummary;
        public static string CustomAxes;
        public static string CustomAxesEditor;
        public static string DarkPen;
        public static string DataSet;
        public static string DataSource;
        public static string DataTableTool;
        public const string DataTableToolDesc = "Series Data Table";
        public static string DataTableToolSummary;
        public static string DateTime;
        public static string DateTimeFormat;
        public static string Default;
        public static string DefaultDemoTee;
        public static string DefaultEditorHeight = "347";
        public static string DefaultEditorSize = "414";
        public static string DefaultFontName;
        public static string DefaultFontSize = "8";
        public static string DefaultPercentOf;
        public static string DefaultPercentOf2;
        public static string DefaultTheme;
        public const string DefLogValueFormat = "#.0 \"x10\" E+0";
        public const string DefPercentFormat = "##0.## %";
        public const string DefValueFormat = "#,##0.###";
        public static string Delete;
        public static string DeltaPointSeries;
        public static string DepthAxis;
        public static string DepthTopAxis;
        public static string DesignFolderNotFound;
        public static string DesiredIncrement;
        public static string DiagCross;
        public static string Diamond;
        public static string DotFrame;
        public static string Dotted;
        public static string Down;
        public static string DownTri;
        public const string DragMarksDesc = "Moves Series marks when dragging them with mouse.";
        public static string DragMarksSummary;
        public static string DragMarksTool;
        public static string DragPoint;
        public const string DragPointDesc = "Moves a Series point when dragging it with mouse.";
        public static string DragPointSummary;
        public const string DrawLineDesc = "Allows drawing custom lines by dragging the mouse.";
        public static string DrawLineSummary;
        public static string DrawLineTool;
        public static string Edit;
        public static string EditChart;
        public static string Editing;
        public static string Ellipse;
        public static string EMFFilter;
        public static string EmptyTeeFile;
        public static string EnterDateTime;
        public static string ExcelFilter;
        public static string ExcelTheme;
        public static string ExpAverageWeight;
        public static string ExpFinish;
        public static string Exploded;
        public static string ExpNext;
        public static string ExportChart;
        public static string ExportPanelNotSet;
        public const string ExtraLegendDesc = "Displays a custom legend at any location inside Chart.";
        public static string ExtraLegendSummary;
        public static string ExtraLegendTool;
        public static string ExtrOut;
        public static string FaderTool;
        public static string FaderToolSummary;
        public static string FibonacciTool;
        public static string FibonacciToolDesc;
        public static string FieldNotFound;
        public const char FieldsSeparator = '\t';
        public static string FileSize;
        public static string Filled;
        public static string FillSample;
        public static string First;
        public static string FittingError;
        public static string FlexFilter;
        public static string Foot;
        public static string FunctionAdd;
        public static string FunctionADX;
        public static string FunctionAverage;
        public static string FunctionBollinger;
        public static string FunctionCCI;
        public static string FunctionCLV;
        public static string FunctionCompress;
        public static string FunctionCompressOHLC;
        public static string FunctionCorrelation;
        public static string FunctionCount;
        public static string FunctionCross;
        public static string FunctionCumulative;
        public static string FunctionCurveFitting;
        public static string FunctionCustom;
        public static string FunctionDivide;
        public static string FunctionDownSampling;
        public static string FunctionExpAverage;
        public static string FunctionExpMovAve;
        public static string FunctionExpTrend;
        public static string FunctionHigh;
        public static string FunctionHistogram;
        public static string FunctionLogTrend;
        public static string FunctionLow;
        public static string FunctionMACD;
        public static string FunctionMedian;
        public static string FunctionMode;
        public static string FunctionMomentum;
        public static string FunctionMomentumDiv;
        public static string FunctionMovingAverage;
        public static string FunctionMultiply;
        public static string FunctionNone;
        public static string FunctionOBV;
        public static string FunctionPerf;
        public static string FunctionPerimeter;
        public static string FunctionPeriod;
        public static string FunctionPVO;
        public static string FunctionRMS;
        public static string FunctionRSI;
        public static string FunctionSAR;
        public static string FunctionSmooth;
        public static string FunctionStdDeviation;
        public static string FunctionStochastic;
        public static string FunctionSubtract;
        public static string FunctionTrend;
        public static string FunctionVariance;
        public static string FunnelBelow;
        public static string FunnelExceed;
        public static string FunnelPercent;
        public static string FunnelSegment;
        public static string FunnelSeries;
        public static string FunnelWithin;
        public static string Gallery3D;
        public static string GalleryArea;
        public static string GalleryArrow;
        public static string GalleryBar;
        public static string GalleryBar3D;
        public static string GalleryBarJoin;
        public static string GalleryBezier;
        public static string GalleryBigCandle;
        public static string GalleryBoxPlot;
        public static string GalleryBubble;
        public static string GalleryCandle;
        public static string GalleryCircled;
        public static string GalleryCircularGauge;
        public static string GalleryClock;
        public static string GalleryColorGrid;
        public static string GalleryContour;
        public static string GalleryCursor;
        public static string GalleryDarvas;
        public static string GalleryDonut;
        public static string GalleryError;
        public static string GalleryErrorBar;
        public static string GalleryExtended;
        public static string GalleryFastLine;
        public static string GalleryFinancial;
        public static string GalleryFunctions;
        public static string GalleryGantt;
        public static string GalleryGauge;
        public static string GalleryGauges;
        public static string GalleryHighLow;
        public static string GalleryHistogram;
        public static string GalleryHorizBar;
        public static string GalleryHorizBoxPlot;
        public static string GalleryHorizLine;
        public static string GalleryIsoSurface;
        public static string GalleryKagi;
        public static string GalleryLine;
        public static string GalleryLinearGauge;
        public static string GalleryLinePoint;
        public static string GalleryLogoFont;
        public static string GalleryMap;
        public static string GalleryNumericGauge;
        public static string GalleryOrgChart;
        public static string GalleryPie;
        public static string GalleryPoint;
        public static string GalleryPoint3D;
        public static string GalleryPointFigure;
        public static string GalleryPolar;
        public static string GalleryPolarBar;
        public static string GalleryPyramid;
        public static string GalleryRadar;
        public static string GalleryRenko;
        public static string GallerySamples;
        public static string GalleryShape;
        public static string GallerySmith;
        public static string GalleryStandard;
        public static string GalleryStats;
        public static string GallerySurface;
        public static string GalleryTagCloud;
        public static string GalleryTower;
        public static string GalleryTriSurface;
        public static string GalleryVector3D;
        public static string GalleryVerticalLinearGauge;
        public static string GalleryVolume;
        public static string GalleryVolumePipe;
        public static string GalleryWaterFall;
        public static string GalleryWindRose;
        public static string GalleryWorldMap;
        public static string GalleryWorldMaps;
        public static string GanttSample1;
        public static string GanttSample10;
        public static string GanttSample2;
        public static string GanttSample3;
        public static string GanttSample4;
        public static string GanttSample5;
        public static string GanttSample6;
        public static string GanttSample7;
        public static string GanttSample8;
        public static string GanttSample9;
        public static string GanttTool;
        public const string GanttToolDesc = "Allows dragging and resizing Gantt bars.";
        public static string GanttToolSummary;
        public static string GIFFilter;
        public static string Gradient;
        public static string GrayscaleTheme;
        public static string Grid3D;
        public const string GridBandDesc = "Grid Band tool, use it to display a coloured rectangles (bands) at the grid lines of the specified axis and position.";
        public static string GridBandSummary;
        public static string GridBandTool;
        public static string GridTranspose;
        public const string GridTransposeDesc = "Exchanges X and Z coordinates to rotate Series 90 degree.";
        public static string GridTransposeSummary;
        public static string GroupName;
        public static string Height;
        public static string HelperScriptAnnotation;
        public static string Hollow;
        public static string HorizAreaSeries;
        public static string HorizHistogramSeries;
        public static string HorizLine;
        public static string HotspotSummary;
        public static string HotspotTool;
        public static string HTMLFilter;
        public static string Image;
        public static string ImageBarSeries;
        public static string ImagePointSeries;
        public static string ImageTool;
        public static string ImageToolSummary;
        public static string ImportChart;
        public static string ImportTeeChart;
        public static string ImportTeeChartFile;
        public static string IncorrectMaxMinValue;
        public static string Index;
        public static string Insert;
        public static string InvalidEditorClass;
        public static string InvalidTeeFile;
        public static string InvPyramid;
        public static string JPEGFilter;
        public static string Labels;
        public static string Last;
        public static string LEDGauge;
        public static string LeftAxis;
        public static string Legend;
        public static string LegendColorWidth;
        public static string LegendFirstValue;
        public const string LegendPaleteToolDesc = "Displays legend made with 3D series palette colors.";
        public static string LegendPaletteTool;
        public static string LegendPaletteToolSummary;
        public const string LegendScrollBarDesc = "Displays a scrollbar at Chart Legend to enable scroll it by dragging the mouse.";
        public static string LegendScrollBarSummary;
        public static string LightTool;
        public const string LightToolDesc = "Contains a Chart Tool that displays a 2 dimensional \"light\" effect over the chart Canvas.";
        public static string LightToolSummary;
        public static string Line;
        public static string Lines;
        public const char LineSeparator = '\n';
        public static string Load;
        public static string LoadChart;
        public static string LowBezierPoints;
        public static string Magnify;
        public static string MagnifySummary;
        public static string MappingAfrica;
        public static string MappingAsia;
        public static string MappingAustralia;
        public static string MappingCentralAmerica;
        public static string MappingEurope;
        public static string MappingEurope15;
        public static string MappingEurope27;
        public static string MappingMiddleEast;
        public static string MappingNorthAmerica;
        public static string MappingSouthAmerica;
        public static string MappingSpain;
        public static string MappingUSA;
        public static string MappingUSAHawaiiAlaska;
        public static string MappingWorld;
        public static string MapSeries;
        public static string MarkerTool;
        public static string Marks;
        public const string MarksTipDesc = "Displays \"tips\" or \"hints\" when the end-user moves or clicks the mouse over a series point.";
        public static string MarksTipSummary;
        public static string MarksTipTool;
        public static string Maximum;
        public static string MaxPointsPerPage;
        public static string MildOut;
        public static string Minimum;
        public static string MissingEditorClass;
        public const string NearestPointDesc = "Displays a graphical signal when the mouse is moving near a series point.";
        public static string NearestPointSummary;
        public static string NearestTool;
        public static string NewSeriesTitle;
        public static string Next;
        public static string No;
        public static string NoBorder;
        public static string NoCircle;
        public static string NoGrid;
        public static string NoHigh;
        public static string NoLine;
        public static string NoLines;
        public static string NoLow;
        public static string None;
        public static string NoPoint;
        public static string Normal;
        public static string NoSeriesSelected;
        public static string OnlineSupport;
        public static string OpenTeeChartFile;
        public static string OpenTextFile;
        public static string OpenXmlThemeFile;
        public static string OperaTheme;
        public static string OpportunityValues;
        public static string Options;
        public static string Origin;
        public static string PageNumber;
        public static string PageOfPages;
        public static string Patterns;
        public static string PCXFilter;
        public static string PDFFilter;
        public static string Percent3D;
        public static string Period;
        public static string PeriodRange;
        public static string PieOther;
        public static string PieSample1;
        public static string PieSample2;
        public static string PieSample3;
        public static string PieSample4;
        public static string PieSample5;
        public static string PieSample6;
        public static string PieSample7;
        public static string PieSample8;
        public static string PieTool;
        public const string PieToolDesc = "Outlines or expands Pie slices when moving or clicking with mouse.";
        public static string PieToolSummary;
        public static string PNGFilter;
        public static string Point2D;
        public static string Points;
        public const string PolarDegreeSymbol = "\x00ba";
        public static string PolarGridSeries;
        public static string PolyDegreeRange;
        public static string Positions;
        public static string Post;
        public static string Preview;
        public static string PrintPreview;
        public static string Prior;
        public static string Property;
        public static string PSFilter;
        public static string Pyramid;
        public static string QuoteValues;
        public static string RandomTheme;
        public static string Rectangle;
        public static string RectangleTool;
        public const string RectangleToolDesc = "Displays custom text at any location inside Chart within a resizable box.";
        public static string RefreshData;
        public static string RefreshInterval;
        public static string RightAxis;
        public const string RotateDesc = "Allows rotating Chart dragging with mouse button.";
        public static string RotateSummary;
        public static string RotateTool;
        public static string SaveChart;
        public static string SaveChartToFile;
        public static string Scale;
        public static string ScrollBarTool;
        public static string ScrollTool;
        public const string ScrollToolDesc = "Provides clientside Chart scroll functionality for WebCharts on a WebForm";
        public static string ScrollToolSummary;
        public static string SelectedSeries;
        public static string SelectFolder;
        public static string SelectorTool;
        public const string SelectorToolDesc = "This tool enables the end-user to click and drag chart elements like series, axes, legend, titles, etc.";
        public static string SelectorToolSummary;
        public static string SelectPictureFile;
        public static string SelfStack;
        public static string SemiPie;
        public static string Separator;
        public static string Series;
        public const string SeriesAnimationDesc = "Performs growing animation of Series points.";
        public static string SeriesAnimationSummary;
        public static string SeriesAnimTool;
        public static string SeriesBandTool;
        public const string SeriesBandToolDesc = "Use it to display a band between two (line) series.";
        public static string SeriesBandToolSummary;
        public static string SeriesDelete;
        public const string SeriesHotspotDesc = "Displays \"tips\" or \"hints\" or provides drilldown capacity when the end-user moves or clicks the mouse over a series point.";
        public static string SeriesInvDataSource;
        public static string SeriesList;
        public static string SeriesParentNoSelf;
        public static string SeriesRegionTool;
        public static string SeriesRegionToolSummary;
        public static string SeriesSetDataSource;
        public static string SeriesStatsTool;
        public const string SeriesStatsToolDesc = "Statistics";
        public static string SeriesStatsToolSummary;
        public static string SeriesTextFieldZero;
        public static string SeriesTranspose;
        public const string SeriesTransposeDesc = "Transpose series";
        public static string SeriesTransposeSummary;
        public static string Shadow;
        public static string ShapeGallery1;
        public static string ShapeGallery2;
        public static string SideAll;
        public static string Sides;
        public static string SingleColor;
        public static string SingleRecord;
        public static string SmallDotsPen;
        public static string SmithReactance;
        public static string SmithResistance;
        public static string Stack;
        public static string Stack100;
        public static string Stairs;
        public static string Star;
        public static string SubChartChartName;
        public static string SubChartNewChart;
        public static string SubChartNewName;
        public static string SubChartRenameChart;
        public static string SubChartTool;
        public static string SubChartToolSummary;
        public static string Summary;
        public static string SupportURL;
        public static string SureToApply;
        public static string SureToDelete;
        public static string SurfaceNearestTool;
        public const string SurfaceNearestToolDesc = "Displays a visual indication of selecting a Surface cell when the user moves the mouse over a surface series.";
        public static string SurfaceNearestToolSummary;
        public static string SVGFilter;
        public static string TabDelimiter = "\t";
        public const string TeeChart = "TeeChart";
        public static string TeeChartExceptionString;
        public const string TeeChartPocketEval = "TeeChart Evaluation for Pocket.NET";
        public static string TeeChartTheme;
        public static string TeeFiles;
        public static string TeeFilesExtension;
        public static string TENFilter;
        public static string Test;
        public static string Text;
        public static string TextFile;
        public static string TextFilter;
        public static string TextSrcURL;
        public static string Themes;
        public static string ThemeSelector;
        public static string TIFFFilter;
        public static string Title;
        public static string TopAxis;
        public static ITranslator Translator;
        public static string Transparency;
        public static string Triangle;
        public static string TriSurfaceAllColinear;
        public static string TriSurfaceLess;
        public static string TriSurfaceSimilar;
        public static string TxtFilesExtension;
        public static string Up;
        public static string Value;
        public static string ValuesAngle = "Angle";
        public static string ValuesArrowEndX = "EndX";
        public static string ValuesArrowEndY = "EndY";
        public static string ValuesBar = "Bar";
        public static string ValuesBubbleRadius = "Radius";
        public static string ValuesClose;
        public static string ValuesDate;
        public static string ValuesFormat;
        public static string ValuesGanttEnd = "End";
        public static string ValuesGanttNextTask = "NextTask";
        public static string ValuesGanttStart = "Start";
        public static string ValuesHigh;
        public static string ValuesLow;
        public static string ValuesOffset;
        public static string ValuesOpen;
        public static string ValuesPie = "Pie";
        public static string ValuesStdError;
        public static string ValuesVectorEndZ;
        public const string ValuesX = "X";
        public const string ValuesY = "Y";
        public const string ValuesZ = "Z";
        public static string VertLine;
        public static string View3D;
        public static string VMLFilter;
        public static string WarningHIColor;
        public static string WEBTheme;
        public static string WireFrame;
        public static string WizardSureToClose;
        public static string WizardTab;
        public static string WMFFilter;
        public static string WrongTeeFileFormat;
        public static string XAMLFilter;
        public static string XMLFile;
        public static string XMLFilter;
        public static string XPTheme;
        public static string Yes;
        public static string ZoomTool;
        public const string ZoomToolDesc = "Provides clientside Chart zoom functionality for WebCharts on a WebForm";
        public static string ZoomToolSummary;

        protected Texts()
        {
        }
    }
}

