namespace QWhale.Editor
{
    using QWhale.Common;
    using QWhale.Editor.CodeCompletion;
    using QWhale.Editor.TextSource;
    using System;
    using System.Drawing;
    using System.Windows.Forms;

    public class EditConsts
    {
        public static string CharsTag = @"\[chars]";
        public static string ColumnSeparator = "|";
        public static string DateTag = @"\[date]";
        public static int DefaltScrollSplitterSize = 6;
        public static Color DefaultArrowBackColor = Color.Silver;
        public static Color DefaultArrowForeColor = Color.Black;
        public static string DefaultAutoCorrectDelimiters = (" .,;:" + '\r' + '\t');
        public static int DefaultBookMarkImageIndex = 10;
        public const EditBorderStyle DefaultBorderStyle = EditBorderStyle.Fixed3D;
        public static Color DefaultBracesBackColor = Color.Empty;
        public static int DefaultBracesDelay = 0x7d0;
        public static FontStyle DefaultBracesFontStyle = FontStyle.Bold;
        public static Color DefaultBracesForeColor = Color.Black;
        public static int DefaultCaretWidth = 2;
        public static char[] DefaultClosingBraces = new char[] { ')', ']', '}' };
        public static string DefaultCodeCompletionChars = ".(";
        public static CodeCompletionFlags DefaultCodeCompletionFlags = (CodeCompletionFlags.AcceptOnTab | CodeCompletionFlags.AcceptOnDelimiter | CodeCompletionFlags.FeetToScreen | CodeCompletionFlags.AcceptOnDblClick | CodeCompletionFlags.CloseOnLostFocus | CodeCompletionFlags.CloseOnMouseLeave | CodeCompletionFlags.AcceptOnEnter | CodeCompletionFlags.CloseOnEscape);
        public static string DefaultCodeCompletionFont = "Tahoma";
        public static float DefaultCodeCompletionFontSize = 8.5f;
        public static int DefaultCollasedImageWidth = 8;
        public static int DefaultColumnMarginPosition = 0x10;
        public static int DefaultColumnSeparator = 2;
        public static Color DefaultColumnsIndentForeColor = SystemColors.ControlLight;
        public static FontStyle DefaultCommentsFontStyle = FontStyle.Italic;
        public static int DefaultCompletionStartDelay = 100;
        public static Color DefaultContentDividerColor = Color.Gray;
        public static string DefaultDelimiters = ";.,:'\"{}[]()?!@#$%^&*-+=|\\/<>";
        public static Color DefaultDisabledForeColor = SystemColors.GrayText;
        public static int DefaultDragDelay = 500;
        public static int DefaultDropDownCount = 8;
        public static Color DefaultGutterBackColor = SystemColors.Control;
        public static Color DefaultGutterForeColor = Color.Gray;
        public static GutterOptions DefaultGutterOptions = (GutterOptions.PaintLineModificators | GutterOptions.PaintBookMarks);
        public static int DefaultGutterWidth = 0x10;
        public static Color DefaultHeaderFontColor = Color.LightGray;
        public static FontStyle DefaultHeaderFontStyle = FontStyle.Regular;
        public static int DefaultHideHintDelay = 0x9c4;
        public static Color DefaultHighlightBackColor = SystemColors.Highlight;
        public static Color DefaultHighlightForeColor = SystemColors.HighlightText;
        public static int DefaultHintDelay = 500;
        public static int DefaultHintOffsetX = 8;
        public static int DefaultHintOffsetY = 4;
        public static int DefaultHorzScrollDelta = 5;
        public static int DefaultHorzScrollSize = 0xff;
        public static Color DefaultHyperTextForeColor = Color.Blue;
        public static Color DefaultInactiveHighlightBackColor = SystemColors.InactiveCaption;
        public static Color DefaultInactiveHighlightForeColor = SystemColors.InactiveCaptionText;
        public static IndentOptions DefaultIndentOptions = (IndentOptions.SmartIndent | IndentOptions.AutoIndent);
        public static Color DefaultInfoBackColor = SystemColors.Info;
        public static Color DefaultLineBookmarksColor = Color.Red;
        public static Color DefaultLineModificatorChangedColor = Color.Yellow;
        public static Color DefaultLineModificatorSavedColor = Color.Lime;
        public static int DefaultLineModificatorWidth = 4;
        public static Color DefaultLineNumbersBackColor = SystemColors.Window;
        public static Color DefaultLineNumbersForeColor = Color.Teal;
        public static int DefaultLineNumbersIndent = 2;
        public static int DefaultLineNumbersStart = 1;
        public static Color DefaultLineSeparatorColor = SystemColors.ScrollBar;
        public static Color DefaultLineSeparatorLineColor = SystemColors.ControlText;
        public static Color DefaultLineStyleBackColor = SystemColors.Window;
        public static Color DefaultLineStyleForeColor = SystemColors.WindowText;
        public static LineStyleOptions DefaultLineStyleOptions = LineStyleOptions.InvertColors;
        public static Color DefaultMarginColumnForeColor = Color.LightGray;
        public static Color DefaultMarginForeColor = Color.Gray;
        public static int DefaultMarginHitWidth = 4;
        public static int DefaultMarginPosition = 80;
        public static int DefaultMinListBoxHeight = 50;
        public static int DefaultMinListBoxWidth = 50;
        public static NavigateOptions DefaultNavigateOptions = (NavigateOptions.DownAtLineEnd | NavigateOptions.UpAtLineBegin);
        public static char[] DefaultOpenBraces = new char[] { '(', '[', '{' };
        public static int DefaultOutlineDelay = 0x3e8;
        public static Color DefaultOutlineForeColor = Color.DarkGray;
        public static OutlineOptions DefaultOutlineOptions = (OutlineOptions.ShowHints | OutlineOptions.DrawButtons | OutlineOptions.DrawLines);
        public static string DefaultOutlineText = "...";
        public static int DefaultOutliningIndent = 1;
        public static Color DefaultPageBackColor = Color.FromArgb(0x65, 0x91, 0xcd);
        public static Color DefaultPageBorderColor = SystemColors.WindowFrame;
        public static int DefaultPageHorzOffset = 0x40;
        public static int DefaultPageMargin = 100;
        public static int DefaultPageMarginSize = 0x18;
        public static int DefaultPageVertOffset = 0x18;
        public static int DefaultParserDelta = 0x80;
        public static Color DefaultPrintHeaderForeColor = Color.Black;
        public const int DefaultPrintHeaderOffsetX = 0x18;
        public const int DefaultPrintHeaderOffsetY = 8;
        public static PrintOptions DefaultPrintOptions = (PrintOptions.DisplayProgress | PrintOptions.UseFooter | PrintOptions.UseHeader | PrintOptions.UseSyntax | PrintOptions.UseColors | PrintOptions.WordWrap | PrintOptions.PageNumbers | PrintOptions.LineNumbers);
        public static int DefaultRowSeparator = 2;
        public static Color DefaultRulerBackColor = Color.FromArgb(0x9b, 0xbb, 0xe3);
        public static string DefaultRulerFontName = "Arial";
        public static float DefaultRulerFontSize = 7f;
        public static int DefaultRulerHeight = 0x1c;
        public static int DefaultRulerHitWidth = 4;
        public static Color DefaultRulerIndentBackColor = Color.FromArgb(0xb1, 0xca, 0xeb);
        public static int DefaultRulerIndentSize = 2;
        public static int DefaultRulerMinWidth = 40;
        public static RulerOptions DefaultRulerOptions = (RulerOptions.DisplayDragLine | RulerOptions.AllowDrag | RulerOptions.Discrete);
        public static RulerUnits DefaultRulerUnits = RulerUnits.Inches;
        public static int DefaultScrollDeltaRatio = 5;
        public static ScrollingOptions DefaultScrollingOptions = (ScrollingOptions.SystemScrollbars | ScrollingOptions.UseScrollDelta | ScrollingOptions.SmoothScroll);
        public static SearchOptions DefaultSearchOptions = (SearchOptions.CycledSearch | SearchOptions.FindSelectedText | SearchOptions.FindTextAtCursor);
        public static int DefaultSelDelay = 0x20;
        public static Color DefaultSelectionBorderColor = SystemColors.InactiveCaption;
        public static Color DefaultSelectionDragColor = Color.Chocolate;
        public static AllowedSelectionMode DefaultSelectionMode = (AllowedSelectionMode.Block | AllowedSelectionMode.Stream);
        public static SelectionOptions DefaultSelectionOptions = (SelectionOptions.CopyLineWhenEmpty | SelectionOptions.ClearOnDrag | SelectionOptions.SmartFormat | SelectionOptions.OverwriteBlocks);
        public static int DefaultSmoothScrollDelay = 10;
        public static int DefaultSmoothScrollPause = 300;
        public static int DefaultSmoothScrollSteps = 10;
        public static Color DefaultSnippetBackColor = Color.LightSteelBlue;
        public static string DefaultSnippetEndPattern = "end";
        public static string DefaultSnippetPattern = "[a-zA-Z_][a-zA-Z0-9_]*";
        public static string DefaultSnippetSelectedPattern = "selected";
        public static int DefaultSpacesInTab = 4;
        public static string DefaultSpellDelimiters = DefaultDelimiters;
        public static Color DefaultSpellForeColor = Color.Red;
        public static int DefaultTabStop = 4;
        public static Color DefaultTransparentColor = Color.Fuchsia;
        public static UndoOptions DefaultUndoOptions = (UndoOptions.UndoAfterSave | UndoOptions.GroupUndo | UndoOptions.AllowUndo);
        public static string DefaultUrlChars = "_.:/@-?=~&;%+";
        public static FontStyle DefaultUrlFontStyle = FontStyle.Underline;
        public static Color DefaultUrlForeColor = Color.Blue;
        public static Color DefaultUserMarginBackColor = SystemColors.Window;
        public static Color DefaultUserMarginForeColor = SystemColors.ControlText;
        public static string DefaultUserMarginText = @"\[chars] chars";
        public static int DefaultUserMarginWidth = 80;
        public static Color DefaultWhiteSpaceForeColor = Color.Teal;
        public static int DefaultWrapDelta = 0x80;
        public static int DefaultWrapImageIndex = 13;
        public static string DottedText = "...";
        public static char EofSymbol = '_';
        public static char EolSymbol = '\x00b6';
        public static string FileProtocol = "FILE://";
        public static string FTPProtocol = "FTP://";
        public static string GopherProtocol = "GOPHER://";
        public static string HeaderFontName = "Times New";
        public static string HTTPProtocol = "HTTP://";
        public static string LineTag = @"\[line]";
        public static string MailTo = "MAILTO:";
        public static int MaxDropDownCount = 10;
        public static int MaxFontSize = 0x400;
        public static int MaxHintWindowCount = 20;
        public static int MaxHintWindowWidth = ((Screen.PrimaryScreen.Bounds.Width * 2) / 3);
        public static int MaxPaintChar = 0x400;
        public const int MinPageIndent = 4;
        public static Keys[] NavKeys = new Keys[] { Keys.Left, Keys.Right, Keys.Up, Keys.Down, Keys.PageUp, Keys.Next, Keys.End, Keys.Home, Keys.Tab };
        public static string PagesTag = @"\[pages]";
        public static string PageTag = @"\[page]";
        public static char SpaceSymbol = '\x00b7';
        public static char TabSymbol = '→';
        public static string TimeTag = @"\[time]";
        public static string UserTag = @"\[username]";
        public const int WheelDelta = 120;
        public static char WordWrapSymbol = '…';
        public static string WWW = "WWW.";
    }
}

